### ISSUE TITLE
Time to change back to black is getting longer and longer...

### ISSUE THREAD

**Issue by Mikkey12** [werthdavid/MMM-BurnIn#2]
Hey, first of all, thanks for your cool module, I definitely need something like this. And it's also working, with just one problem: With each change the time to switch back to black is getting longer by approx. 3sec. No problem in the beginning, but after a certain time the screens stays white for quite a long time. Any idea what this could be? What additional information do you need?
Thanks in advance, Marc

**Comment by werthdavid** [comment]
Oh wow... I have no idea how that comes but I'll look into it..

**Comment by Mikkey12** [comment]
Hey David,
no hurry. Thanks again for your work, I really appriciate it!
Kind regards,
Marc

**Comment by werthdavid** [comment]
Please try with the latest version ;-)

**Comment by Mikkey12** [comment]
Hi David,

Update done, I will give you an update as soon as possible.

Have a nice evening
Marc

Am Mi., 13. Jan. 2021 um 11:36 Uhr schrieb David Werth <
notifications@github.com>:

**Comment by Mikkey12** [comment]
Hey David,

It's been working now since 3 days, and till now no problem anymore. Looks
like you were successful. Thanks again, I appreciate it!

Have a nice evening
Marc

Am Mi., 13. Jan. 2021 um 11:36 Uhr schrieb David Werth <
notifications@github.com>:

**Comment by werthdavid** [comment]
Hey Marc, 
great to hear that!
Stay safe
